-- LootTableExtreme Database
-- Contains enemy loot tables for WoW Classic

LootTableExtreme.Database = {}
local DB = LootTableExtreme.Database

-- Item quality constants
DB.Quality = {
    POOR = 0,
    COMMON = 1,
    UNCOMMON = 2,
    RARE = 3,
    EPIC = 4,
}

-- Enemy loot table
-- This is populated by ScrapedDatabase.lua which is auto-generated by the scraper
DB.EnemyLoot = {}

-- NPC ID to enemy name lookup
DB.NpcIdToName = {}

-- Reverse lookup: Find which enemies drop a specific item
-- This is built dynamically from the enemy loot table
DB.ItemSources = {}

function DB:BuildItemSourcesCache()
    self.ItemSources = {}
    self.NpcIdToName = {}
    
    for enemyName, enemyData in pairs(self.EnemyLoot) do
        -- Build NPC ID index
        if enemyData.npcId then
            self.NpcIdToName[enemyData.npcId] = enemyName
        end
        
        if enemyData.loot then
            for _, item in ipairs(enemyData.loot) do
                if not self.ItemSources[item.itemId] then
                    self.ItemSources[item.itemId] = {}
                end
                
                table.insert(self.ItemSources[item.itemId], {
                    enemyName = enemyName,
                    dropChance = item.dropChance,
                    zone = enemyData.zone,
                    level = enemyData.level,
                    elite = enemyData.elite or false,
                })
            end
        end
    end
    
    -- Sort each item's sources by drop chance (highest first)
    for itemId, sources in pairs(self.ItemSources) do
        table.sort(sources, function(a, b)
            return a.dropChance > b.dropChance
        end)
    end
end

-- Get loot table for a specific enemy
-- Enriches the data with item information from WoW API
function DB:GetEnemyLoot(enemyName)
    local enemyData = self.EnemyLoot[enemyName]
    if not enemyData then
        return nil
    end
    
    -- Enrich loot data with WoW item information
    if enemyData.loot then
        for _, item in ipairs(enemyData.loot) do
            if not item.name then
                -- Fetch item data from WoW API
                local itemName, itemLink, itemQuality, _, _, _, _, _, _, itemTexture = GetItemInfo(item.itemId)
                if itemName then
                    item.name = itemName
                    item.quality = itemQuality or DB.Quality.COMMON
                    item.texture = itemTexture
                    
                    -- Check if it's a quest item by scanning tooltip
                    item.isQuestItem = self:IsQuestItem(item.itemId)
                end
            end
        end
    end
    
    return enemyData
end

-- Get loot table by NPC ID
function DB:GetEnemyLootByNpcId(npcId)
    local enemyName = self.NpcIdToName[npcId]
    
    if enemyName then
        local data = self:GetEnemyLoot(enemyName)
        return data, enemyName
    end
    return nil, nil
end

-- Helper function to count table entries
function DB:TableCount(tbl)
    local count = 0
    for _ in pairs(tbl) do
        count = count + 1
    end
    return count
end

-- Check if an item is a quest item
function DB:IsQuestItem(itemId)
    -- Create a hidden tooltip to scan the item
    if not self.scanTooltip then
        self.scanTooltip = CreateFrame("GameTooltip", "LootTableExtremeScanTooltip", nil, "GameTooltipTemplate")
        self.scanTooltip:SetOwner(UIParent, "ANCHOR_NONE")
    end
    
    self.scanTooltip:ClearLines()
    self.scanTooltip:SetHyperlink("item:" .. itemId)
    
    -- Check tooltip lines for quest-related text
    for i = 1, self.scanTooltip:NumLines() do
        local line = getglobal("LootTableExtremeScanTooltipTextLeft" .. i)
        if line then
            local text = line:GetText()
            if text and (string.find(text, "Quest") or string.find(text, "Unique")) then
                return true
            end
        end
    end
    
    return false
end

function DB:GetTopItemSources(itemId, maxResults)
    maxResults = maxResults or 3
    local sources = self.ItemSources[itemId]
    
    if not sources then
        return {}
    end
    
    local result = {}
    for i = 1, math.min(maxResults, #sources) do
        table.insert(result, sources[i])
    end
    
    return result
end

-- Search for enemies by name
function DB:SearchEnemies(searchTerm)
    searchTerm = string.lower(searchTerm)
    local results = {}
    
    for enemyName, enemyData in pairs(self.EnemyLoot) do
        if string.find(string.lower(enemyName), searchTerm, 1, true) then
            table.insert(results, {
                name = enemyName,
                zone = enemyData.zone,
                level = enemyData.level,
            })
        end
    end
    
    return results
end

-- Get quality color
function DB:GetQualityColor(quality)
    local colors = {
        [self.Quality.POOR] = {r = 0.62, g = 0.62, b = 0.62},
        [self.Quality.COMMON] = {r = 1.0, g = 1.0, b = 1.0},
        [self.Quality.UNCOMMON] = {r = 0.12, g = 1.0, b = 0.0},
        [self.Quality.RARE] = {r = 0.0, g = 0.44, b = 0.87},
        [self.Quality.EPIC] = {r = 0.64, g = 0.21, b = 0.93},
    }
    
    return colors[quality] or colors[self.Quality.COMMON]
end

-- Get quality text
function DB:GetQualityText(quality)
    local text = {
        [self.Quality.POOR] = "Poor",
        [self.Quality.COMMON] = "Common",
        [self.Quality.UNCOMMON] = "Uncommon",
        [self.Quality.RARE] = "Rare",
        [self.Quality.EPIC] = "Epic",
    }
    
    return text[quality] or "Unknown"
end
